### PR TITLE
small edits to github ch

### PR DESCRIPTION
**Pull request by carriewright11**
I didn't get a chance to review this chapter earlier. This is great @cansavvy! 

Do we want to talk about how the merge might require them to click the force merge button - I remember some students were confused about that in our workshop?

 Maybe adding an image of merging would help.

### CODE REVIEW

**Comment by cansavvy** [comment]
I never merged this chapter, I assumed that must have been you? Anyway thanks for reviewing it now!

**Comment by cansavvy** [comment]
Can you explain what you mean by "force merge"?

**Review by cansavvy — APPROVED** [review]
These look like good changes to me!

**Comment by carriewright11** [comment]
> Can you explain what you mean by "force merge"?
I mean like this: 
Screen Shot 2023-05-10 at 2 53 42 PM

Should we add this?

**Comment by carriewright11** [comment]
> I never merged this chapter, I assumed that must have been you? Anyway thanks for reviewing it now!

hmmm that's odd idk - we can check.  No problem!

**Comment by carriewright11** [comment]
> > Can you explain what you mean by "force merge"?
> > I mean like this:
> > Screen Shot 2023-05-10 at 2 53 42 PM

should we add this?

**Pull request merged**
