### PR TITLE
Style

### PR DESCRIPTION
**Pull request by carriewright11**
#### What changes are being implemented in this Pull Request?

Adding new branding 

### Tell potential reviewers what kind of feedback you are soliciting.

What do you think @cansavvy ?

### CODE REVIEW

**Comment by carriewright11** [comment]
@cansavvy the preview somehow reverted I think - I am pretty sure it was showing an updated version previously

**Comment by carriewright11** [comment]
oh actually nevermind it just needed some more time

**Review by cansavvy — APPROVED** [review]
This looks great!

**Comment by carriewright11** [comment]
> This looks great!

Yay! glad you like it!

**Comment by cansavvy** [comment]
Should we merge this then and then update our other branches? I'm happy to do that right now.

**Comment by carriewright11** [comment]
I can send Roger another email... I am worried about the book.bib file and dictionary getting complicated later - so maybe @cansavvy we should merge it actually?

**Pull request merged**
